--------------------------------------------------------
--  File created - Wednesday-August-10-2016   
--------------------------------------------------------
--------------------------------------------------------
--  DDL for Table XMESO_CONCEPT_DIMENSION
--------------------------------------------------------

  CREATE TABLE "XMESO_CONCEPT_DIMENSION" 
   (	"CONCEPT_PATH" VARCHAR2(2100 BYTE), 
	"CONCEPT_CD" VARCHAR2(150 BYTE), 
	"NAME_CHAR" VARCHAR2(4000 BYTE), 
	"CONCEPT_BLOB" CLOB, 
	"UPDATE_DATE" DATE, 
	"DOWNLOAD_DATE" DATE, 
	"IMPORT_DATE" DATE, 
	"SOURCESYSTEM_CD" VARCHAR2(150 BYTE), 
	"UPLOAD_ID" NUMBER(38,0)
   ) PCTFREE 10 PCTUSED 40 INITRANS 1 MAXTRANS 255 NOCOMPRESS LOGGING
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1 BUFFER_POOL DEFAULT)
  TABLESPACE "USERS" 
 LOB ("CONCEPT_BLOB") STORE AS (
  TABLESPACE "USERS" ENABLE STORAGE IN ROW CHUNK 8192 PCTVERSION 10
  NOCACHE LOGGING 
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1 BUFFER_POOL DEFAULT)) ;
--------------------------------------------------------
--  DDL for Table XMESO_OBSERVATION_FACT
--------------------------------------------------------

  CREATE TABLE "XMESO_OBSERVATION_FACT" 
   (	"ENCOUNTER_NUM" NUMBER(38,0), 
	"PATIENT_NUM" NUMBER(38,0), 
	"CONCEPT_CD" VARCHAR2(50 BYTE), 
	"PROVIDER_ID" VARCHAR2(50 BYTE), 
	"START_DATE" DATE, 
	"MODIFIER_CD" VARCHAR2(100 BYTE), 
	"INSTANCE_NUM" NUMBER(18,0), 
	"VALTYPE_CD" VARCHAR2(50 BYTE), 
	"TVAL_CHAR" VARCHAR2(255 BYTE), 
	"NVAL_NUM" NUMBER(18,5), 
	"VALUEFLAG_CD" VARCHAR2(50 BYTE), 
	"QUANTITY_NUM" NUMBER(18,5), 
	"UNITS_CD" VARCHAR2(50 BYTE), 
	"END_DATE" DATE, 
	"LOCATION_CD" VARCHAR2(50 BYTE), 
	"OBSERVATION_BLOB" CLOB, 
	"CONFIDENCE_NUM" NUMBER(18,5), 
	"UPDATE_DATE" DATE, 
	"DOWNLOAD_DATE" DATE, 
	"IMPORT_DATE" DATE, 
	"SOURCESYSTEM_CD" VARCHAR2(50 BYTE), 
	"UPLOAD_ID" NUMBER(38,0)
   ) PCTFREE 10 PCTUSED 40 INITRANS 1 MAXTRANS 255 NOCOMPRESS LOGGING
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1 BUFFER_POOL DEFAULT)
  TABLESPACE "USERS" 
 LOB ("OBSERVATION_BLOB") STORE AS (
  TABLESPACE "USERS" ENABLE STORAGE IN ROW CHUNK 8192 PCTVERSION 10
  NOCACHE LOGGING 
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1 BUFFER_POOL DEFAULT)) ;
--------------------------------------------------------
--  DDL for Table XMESO_PATIENT_DIMENSION
--------------------------------------------------------

  CREATE TABLE "XMESO_PATIENT_DIMENSION" 
   (	"PATIENT_NUM" NUMBER(38,0), 
	"VITAL_STATUS_CD" VARCHAR2(50 BYTE), 
	"BIRTH_DATE" DATE, 
	"DEATH_DATE" DATE, 
	"SEX_CD" VARCHAR2(50 BYTE), 
	"AGE_IN_YEARS_NUM" NUMBER(38,0), 
	"LANGUAGE_CD" VARCHAR2(50 BYTE), 
	"RACE_CD" VARCHAR2(50 BYTE), 
	"MARITAL_STATUS_CD" VARCHAR2(50 BYTE), 
	"RELIGION_CD" VARCHAR2(50 BYTE), 
	"ZIP_CD" VARCHAR2(10 BYTE), 
	"STATECITYZIP_PATH" VARCHAR2(700 BYTE), 
	"INCOME_CD" VARCHAR2(50 BYTE), 
	"PATIENT_BLOB" CLOB, 
	"UPDATE_DATE" DATE, 
	"DOWNLOAD_DATE" DATE, 
	"IMPORT_DATE" DATE, 
	"SOURCESYSTEM_CD" VARCHAR2(50 BYTE), 
	"UPLOAD_ID" NUMBER(38,0)
   ) PCTFREE 10 PCTUSED 40 INITRANS 1 MAXTRANS 255 NOCOMPRESS LOGGING
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1 BUFFER_POOL DEFAULT)
  TABLESPACE "USERS" 
 LOB ("PATIENT_BLOB") STORE AS (
  TABLESPACE "USERS" ENABLE STORAGE IN ROW CHUNK 8192 PCTVERSION 10
  NOCACHE LOGGING 
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1 BUFFER_POOL DEFAULT)) ;
--------------------------------------------------------
--  DDL for Table XMESO_PROVIDER_DIMENSION
--------------------------------------------------------

  CREATE TABLE "XMESO_PROVIDER_DIMENSION" 
   (	"PROVIDER_ID" VARCHAR2(50 BYTE), 
	"PROVIDER_PATH" VARCHAR2(700 BYTE), 
	"NAME_CHAR" VARCHAR2(850 BYTE), 
	"PROVIDER_BLOB" CLOB, 
	"UPDATE_DATE" DATE, 
	"DOWNLOAD_DATE" DATE, 
	"IMPORT_DATE" DATE, 
	"SOURCESYSTEM_CD" VARCHAR2(50 BYTE), 
	"UPLOAD_ID" NUMBER(38,0)
   ) PCTFREE 10 PCTUSED 40 INITRANS 1 MAXTRANS 255 NOCOMPRESS LOGGING
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1 BUFFER_POOL DEFAULT)
  TABLESPACE "USERS" 
 LOB ("PROVIDER_BLOB") STORE AS (
  TABLESPACE "USERS" ENABLE STORAGE IN ROW CHUNK 8192 PCTVERSION 10
  NOCACHE LOGGING 
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1 BUFFER_POOL DEFAULT)) ;
--------------------------------------------------------
--  DDL for Table XMESO_VISIT_DIMENSION
--------------------------------------------------------

  CREATE TABLE "XMESO_VISIT_DIMENSION" 
   (	"ENCOUNTER_NUM" NUMBER(38,0), 
	"PATIENT_NUM" NUMBER(38,0), 
	"ACTIVE_STATUS_CD" VARCHAR2(50 BYTE), 
	"START_DATE" DATE, 
	"END_DATE" DATE, 
	"INOUT_CD" VARCHAR2(50 BYTE), 
	"LOCATION_CD" VARCHAR2(50 BYTE), 
	"LOCATION_PATH" VARCHAR2(900 BYTE), 
	"LENGTH_OF_STAY" NUMBER(38,0), 
	"VISIT_BLOB" CLOB, 
	"UPDATE_DATE" DATE, 
	"DOWNLOAD_DATE" DATE, 
	"IMPORT_DATE" DATE, 
	"SOURCESYSTEM_CD" VARCHAR2(50 BYTE), 
	"UPLOAD_ID" NUMBER(38,0)
   ) PCTFREE 10 PCTUSED 40 INITRANS 1 MAXTRANS 255 NOCOMPRESS LOGGING
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1 BUFFER_POOL DEFAULT)
  TABLESPACE "USERS" 
 LOB ("VISIT_BLOB") STORE AS (
  TABLESPACE "USERS" ENABLE STORAGE IN ROW CHUNK 8192 PCTVERSION 10
  NOCACHE LOGGING 
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1 BUFFER_POOL DEFAULT)) ;
--------------------------------------------------------
--  Constraints for Table XMESO_CONCEPT_DIMENSION
--------------------------------------------------------

  ALTER TABLE "XMESO_CONCEPT_DIMENSION" MODIFY ("CONCEPT_PATH" NOT NULL ENABLE);
 
  ALTER TABLE "XMESO_CONCEPT_DIMENSION" MODIFY ("CONCEPT_CD" NOT NULL ENABLE);
--------------------------------------------------------
--  Constraints for Table XMESO_OBSERVATION_FACT
--------------------------------------------------------

  ALTER TABLE "XMESO_OBSERVATION_FACT" MODIFY ("ENCOUNTER_NUM" NOT NULL ENABLE);
 
  ALTER TABLE "XMESO_OBSERVATION_FACT" MODIFY ("PATIENT_NUM" NOT NULL ENABLE);
 
  ALTER TABLE "XMESO_OBSERVATION_FACT" MODIFY ("CONCEPT_CD" NOT NULL ENABLE);
 
  ALTER TABLE "XMESO_OBSERVATION_FACT" MODIFY ("PROVIDER_ID" NOT NULL ENABLE);
 
  ALTER TABLE "XMESO_OBSERVATION_FACT" MODIFY ("START_DATE" NOT NULL ENABLE);
 
  ALTER TABLE "XMESO_OBSERVATION_FACT" MODIFY ("MODIFIER_CD" NOT NULL ENABLE);
 
  ALTER TABLE "XMESO_OBSERVATION_FACT" MODIFY ("INSTANCE_NUM" NOT NULL ENABLE);
--------------------------------------------------------
--  Constraints for Table XMESO_PATIENT_DIMENSION
--------------------------------------------------------

  ALTER TABLE "XMESO_PATIENT_DIMENSION" MODIFY ("PATIENT_NUM" NOT NULL ENABLE);
--------------------------------------------------------
--  Constraints for Table XMESO_PROVIDER_DIMENSION
--------------------------------------------------------

  ALTER TABLE "XMESO_PROVIDER_DIMENSION" MODIFY ("PROVIDER_ID" NOT NULL ENABLE);
 
  ALTER TABLE "XMESO_PROVIDER_DIMENSION" MODIFY ("PROVIDER_PATH" NOT NULL ENABLE);
--------------------------------------------------------
--  Constraints for Table XMESO_VISIT_DIMENSION
--------------------------------------------------------

  ALTER TABLE "XMESO_VISIT_DIMENSION" MODIFY ("ENCOUNTER_NUM" NOT NULL ENABLE);
 
  ALTER TABLE "XMESO_VISIT_DIMENSION" MODIFY ("PATIENT_NUM" NOT NULL ENABLE);
